### ISSUE TITLE
Cancro(Mi3) Build successful but missing Launcher

### ISSUE THREAD

**Issue by kat0072** [XOSP/manifest#33]
Hi Team, please advice what I missed in device building.

My Mi3 booted fine on my build but missing Home(Launcher) and keep showing "Starting Android....."

**Comment by nilac8991** [comment]
Make sure you done all these: https://github.com/XOSP-Project/platform_manifest#preparing-xosp-for-your-device

**Comment by kat0072** [comment]
yeah missed to add XOSP configs. Thanks I have latest working build.

**Comment by kat0072** [comment]
The Gapps downloading was  very slow from their server so I build mine it took less time than downloading 👍
