### ISSUE TITLE
No Groups In xosp_devices_deps.xml

### ISSUE THREAD

**Issue by opticyclic** [XOSP/manifest#34]
I did repo init like this to reduce bandwidth as I don't need to download the code for devices I am not building.

    repo init -u git://github.com/XOSP-Project/platform_manifest.git -b xosp-n --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips,-exynos5,-intel,-eclipse

However, xosp_devices_deps.xml doesnt contain the groups tag so I ended up cloning a whole load of extra repos :(

Please add `groups="device"` to the manifest.

**Comment by nilac8991** [comment]
Will be done. Thanks for the advice

**Comment by kat0072** [comment]
There are uncommitted changes to the manifest file please do the needful.

kat0072@ubuntu:~/mi3$ repo sync --force-sync
remote: Counting objects: 5, done.        
remote: Compressing objects: 100% (5/5), done.        
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0        
From git://github.com/XOSP-Project/platform_manifest
   4d58a9e..97abcf2  xosp-n     -> origin/xosp-n
error: .repo/manifests/: contains uncommitted changes

**Comment by nilac8991** [comment]
You have local changes made. It's not a ROM source issue

**Comment by kat0072** [comment]
oh really checking

**Comment by kat0072** [comment]
yeah I see custom manifest got created while building rom. Any way to fix the sync issue without deleting it ?

**Comment by nilac8991** [comment]
git reset --hard  in .repo/manifests

**Comment by kat0072** [comment]
thank you

**Comment by kat0072** [comment]
http://en.miui.com/thread-497124-1-1.html

Just created the thread for XOSP ROM

**Comment by opticyclic** [comment]
I'm not sure what all this commenting was about but it seems unrelated to the issue.

The issue still exists though

https://github.com/XOSP-Project/platform_manifest/blob/xosp-n/snippets/xosp_devices_deps.xml#L6-L26
